KIRA!!
nkhs-ha05hc42/hc42-1010-git-work4-1 pull request #1
Opened 2024-11-18 03:02 UTC by harusamewktk

レビューを頼みます

2024-11-18 03:11 UTC, hc421002 requested changes

2024-11-18 03:11 UTC, hc421002 commented on review.txt
> +review test1
1行目と2行目を入れ替えてください

2024-11-18 03:14 UTC, hc421002 requested changes
レビューしました！
コメント個所をご確認ください。

2024-11-18 03:14 UTC, hc421002 commented on review.txt
> +review test1
1行目と2行目を入れ替えてください

2024-11-25 00:46 UTC, harusamewktk commented
@hc421002 
指摘箇所修正完了しています。

2024-11-25 02:26 UTC, hc421002 approved these changes
修正を確認しました！

2024-11-25 02:28 UTC, merged